import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-blue-900 via-purple-900 to-black min-h-screen">
        <div className="relative w-full h-32 overflow-hidden">
          <div className="absolute inset-0 animate-ken-burns">
            <Image 
              src="/metaverse-banner.webp" 
              alt="Metaverse background" 
              fill
              style={{ objectFit: 'cover' }}
              priority
            />
          </div>
          <div className="absolute inset-0 bg-gradient-to-r from-blue-600/80 via-purple-600/80 to-blue-600/80 animate-pulse-slow"></div>
          <div className="absolute inset-0" style={{
            backgroundImage: `
              linear-gradient(to right, rgba(255,255,255,0.1) 1px, transparent 1px),
              linear-gradient(to bottom, rgba(255,255,255,0.1) 1px, transparent 1px)
            `,
            backgroundSize: '20px 20px'
          }}></div>
          <div className="relative h-full flex items-center justify-between px-8 max-w-7xl mx-auto">
            <div className="flex items-center space-x-4">
              <div className="w-10 h-10 relative">
                <Image 
                  src="/logo.webp"
                  alt="Logo"
                  fill
                  style={{ objectFit: 'contain' }}
                  className="rounded-full"
                />
              </div>
              <span className="text-white font-bold text-xl tracking-wider">METAVERSE</span>
            </div>
            <nav className="hidden sm:flex space-x-6">
              <a href="/" className="text-white hover:text-blue-300 transition-colors">Home</a>
              <a href="/about" className="text-white hover:text-blue-300 transition-colors">About</a>
              <a href="/agents" className="text-white hover:text-blue-300 transition-colors">AI Agents</a>
            </nav>
          </div>
          <div className="absolute bottom-0 w-full h-px bg-gradient-to-r from-transparent via-blue-500/50 to-transparent"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
